# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CI

on:
  push:
    branches: ['main', 'redesign']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and deploy
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint
      - run: npm install -g surge
      - if: github.ref == 'refs/heads/redesign'
        run: surge ./build ${{ secrets.TEST_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}   
      - if: github.ref == 'refs/heads/main'
        run: surge ./build ${{ secrets.DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

